### ISSUE TITLE
Qt 5.15 compatibility.

### ISSUE THREAD

**Issue by dmtrbm** [Mahlet-Inc/hobbits#65]
Compilation fails with:
```
peakselector.cpp: In member function ‘virtual void PeakSelector::paintEvent(QPaintEvent*)’:
peakselector.cpp:71:18: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
   71 |     QPainterPath path;
      |                  ^~~~
```
Including QPainterPath with every QPainter fixes it.
Thanks.

**Comment by hello-adam** [comment]
Thanks, I can probably fix this next week. I'd also accept a pull request in the develop branch

**Comment by hello-adam** [comment]
@dmtrbm Let me know if that doesn't fix the build for you (it worked on my Qt 5.15.1)

**Comment by dmtrbm** [comment]
Works here with 5.15.1 too. Thank you.
